### ISSUE TITLE
Support fabric

### ISSUE THREAD

**Issue by klucsik** [cpburnz/minecraft-prometheus-exporter#10]
Hello there,
is there any chance to support FABRIC modloader versions of modpacks?

**Comment by cpburnz** [comment]
I don't have any experience making mods with Fabric. It would take me some time to look into it. It looks like there's an active mod developed for Fabric already that may interest you: [FabricExporter](https://modrinth.com/mod/fabricexporter).

**Comment by cpburnz** [comment]
Support for Minecraft 1.21.1 with Fabric has been released. You can access it [here](https://github.com/cpburnz/minecraft-prometheus-exporter/releases/tag/1.21.1-fabric-1.2.1) or on [Curse Forge](https://www.curseforge.com/minecraft/mc-mods/prometheus-exporter/files/5673131) once it's approved there. 

Now that I have a known working version, backporting to older Minecraft versions shouldn't be difficult.
