### ISSUE TITLE
Porting Prometheus Exporter mod to 1.20.1

### ISSUE THREAD

**Issue by Gaetann18** [cpburnz/minecraft-prometheus-exporter#12]
Hello,

I have been using this mod for many years and I enjoy it very much.

I am writing to you today to ask if you are considering porting your mod to the 1.20.1 version of Minecraft. The 1.20.1 version of Minecraft is the latest version of Minecraft and it was released a few months ago.

I know that you are busy and that you may have other projects in progress, but I would be very grateful if you could port your mod to the 1.20.1 version. I am sure that many other players would be happy to be able to use your mod on the new version of Minecraft.

Thank you for your time and consideration.

Sincerely,

**Comment by cpburnz** [comment]
@Gaetann18 I'm glad this mod has proven useful. I'll look into upgrading 1.20.1. The last few Minecraft updates have had minimal changes so hopefully the trend continues.

**Comment by cpburnz** [comment]
@Gaetann18 I've released v1.0.0 for MC 1.20.1. You can download it from [Github](https://github.com/cpburnz/minecraft-prometheus-exporter/releases/tag/1.20.1-forge-1.0.0) or on [Curse Forge](https://legacy.curseforge.com/minecraft/mc-mods/prometheus-exporter/files/4694230) (once it's approved over there).

**Comment by Gaetann18** [comment]
Thanks for the responsiveness!
