### ISSUE TITLE
[1.7.10] Support

### ISSUE THREAD

**Issue by superhealing** [cpburnz/minecraft-prometheus-exporter#13]
Hey, i'm running quite small number of servers from this ancient versions, mainly GTNH and Lost pack, and i don't use thermos neither two packs, i'm asking if there is chance for this?

**Comment by cpburnz** [comment]
@superhealing I'll look into it. I know there were lots of breaking changes in older versions of Minecraft and Forge, so it will largely depend on how cumbersome the changes are.

**Comment by cpburnz** [comment]
Support for MC 1.7.10 has been released. You can access it [here](https://github.com/cpburnz/minecraft-prometheus-exporter/releases/tag/1.7.10-forge-1.0.0), or on [Curse Forge](https://legacy.curseforge.com/minecraft/mc-mods/prometheus-exporter/files/4964869) once it's approved there.
