### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by zPiiiG** [cpburnz/minecraft-prometheus-exporter#14]
Hi mate, im in love with the project. Me and some friends are playing a modded pack on 1.8.2 and im trying to set up a monitoring system for that version.
Can you please make a version for MC 1.8.2 with forge 40.2.4?
Best regards

**Comment by zPiiiG** [comment]
Hi, i try to manually upload to that version and now its working. No more needed

**Comment by cpburnz** [comment]
@zPiiiG Do you mean you just manually changed the version to MC 1.8.2 and Force 40.2.4 in [build.gradle](https://github.com/cpburnz/minecraft-prometheus-exporter/blob/mc1.12.2/build.gradle) on the mc1.12.2 branch, and it compiled without requiring any other changes?
