### ISSUE TITLE
Forge 1.18.2 Support

### ISSUE THREAD

**Issue by Aiidoneus** [cpburnz/minecraft-prometheus-exporter#18]
Hello,

I was wondering if you support 1.18.2 Forge? I see that you support 1.18.1 but not 2. Could you support this?

**Comment by cpburnz** [comment]
Hi @Aiidoneus, I'll publish a release for 1.18.2.

**Comment by cpburnz** [comment]
Support for MC 1.18.2 has been released. You can access it [here](https://github.com/cpburnz/minecraft-prometheus-exporter/releases/tag/1.18.2-forge-1.1.0), or on [Curse Forge](https://www.curseforge.com/minecraft/mc-mods/prometheus-exporter/files/5255383) once it's approved there.
