### ISSUE TITLE
[NeoForge] Version for 1.20.4

### ISSUE THREAD

**Issue by M0n7y5** [cpburnz/minecraft-prometheus-exporter#23]
Is there even smallest possibility that you can make this compatible with NeoForge?

**Comment by cpburnz** [comment]
NeoForge looks to be a recent fork of Forge. It should be simple for me to make a port for NeoForge.

**Comment by M0n7y5** [comment]
Ah that would be really nice. From all of those metrics plugins around there, this one is the far best.

**Comment by cpburnz** [comment]
Support for Minecraft 1.20.4 with NeoForge has been released. You can access it [here](https://github.com/cpburnz/minecraft-prometheus-exporter/releases/tag/1.20.4-neoforge-1.2.1), or on [Curse Forge](https://www.curseforge.com/minecraft/mc-mods/prometheus-exporter/files/5648779) once it's approved there.
