### ISSUE TITLE
New Version: Minecraft 1.21

### ISSUE THREAD

**Issue by pkatterjohn** [cpburnz/minecraft-prometheus-exporter#25]
Hello! Absolutely love the project! Do you have plans to update to 1.21?

**Comment by cpburnz** [comment]
Support for Minecraft 1.21.1 has been released. You can access it [here](https://github.com/cpburnz/minecraft-prometheus-exporter/releases/tag/1.21.1-forge-1.2.1), or on [Curse Forge](https://www.curseforge.com/minecraft/mc-mods/prometheus-exporter/files/5645842) once it's approved there. If you specifically need Minecraft 1.21.0, just let me know.
