### ISSUE TITLE
Please make a 1.19.2 version for Forge

### ISSUE THREAD

**Issue by Maelstromeous** [cpburnz/minecraft-prometheus-exporter#26]
Hello,

Please could you create a version for Forge on 1.19.2? Many modpacks are pinned to this minecraft version, and it hopefully shouldn't be a massive change on your end to make it work.

Thanks in advance!

**Comment by Maelstromeous** [comment]
Never mind, I'm just blind :')

**Comment by cpburnz** [comment]
@Maelstromeous I'd be nice if Github would allow sorting releases.

I'll make a new release (v1.2.1) for MC 1.19.2 soon since its current version is v1.0.0 which lacks a couple bug fixes and new fields.

**Comment by cpburnz** [comment]
v1.2.1 for Minecraft 1.19.2 has been released. You can access it on [GitHub](https://github.com/cpburnz/minecraft-prometheus-exporter/releases/tag/1.19.2-forge-1.2.1), or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/prometheus-exporter/files/5693718) when it's approved over there.
