### ISSUE TITLE
Backporting to 1.20.1 forge

### ISSUE THREAD

**Issue by KGT1** [cpburnz/minecraft-prometheus-exporter#29]
Hey would you consider backporting the latest changes to 1.20.1 forge?

Would be very much appriciated!

**Comment by cpburnz** [comment]
Hi @KGT1, I'll release an update for 1.20.1 Forge this coming week.

**Comment by cpburnz** [comment]
v1.2.1 for Minecraft 1.20.1 has been released. You can access it on [GitHub](https://github.com/cpburnz/minecraft-prometheus-exporter/releases/tag/1.20.1-forge-1.2.1), or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/prometheus-exporter/files/5869930).
