### ISSUE TITLE
1.21 version specifically

### ISSUE THREAD

**Issue by communistteaparty** [cpburnz/minecraft-prometheus-exporter#30]
Hello! Would you consider making a version for 1.21? I saw the closed issue #25 on a 1.21 version, but unfortunately due to my specific situation I can't use versions higher than 1.21 (mod support). I'm already using the exporter with Grafana for a different server and would like to use it for this newer server as well!

**Comment by cpburnz** [comment]
@communistteaparty Yeah, I'll make a release for 1.21 specifically.

**Comment by cpburnz** [comment]
I've released v1.2.1 for MC 1.21. You can access it on [GitHub](https://github.com/cpburnz/minecraft-prometheus-exporter/releases/tag/1.21.0-forge-1.2.1), or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/prometheus-exporter/files/6011391) (once it's approved). Merry Christmas!

**Comment by communistteaparty** [comment]
I hate to be a nuisance and I should've mentioned it, but I was looking for a fabric version. I appreciate the responses and work btw! And happy holidays to you too :)

**Comment by cpburnz** [comment]
I've now made a release for Fabric. You can access it on [Github](https://github.com/cpburnz/minecraft-prometheus-exporter/releases/tag/1.21.0-fabric-1.2.1), or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/prometheus-exporter/files/6015389) (once it's approved).

**Comment by communistteaparty** [comment]
Absolute chad, thank you.
