### ISSUE TITLE
Minecraft 1.18.1 support?

### ISSUE THREAD

**Issue by nerosnm** [cpburnz/minecraft-prometheus-exporter#4]
Are there any plans to support 1.18.1 with this plugin?

**Comment by caleb-partsgiant** [comment]
@nerosnm I'll take a look at updating to MC 1.18.1. At the moment I'm having trouble with Forge. Getting the right spec for the mappings always gives me trouble.

**Comment by cpburnz** [comment]
@nerosnm I'll take a look at updating to MC 1.18.1. At the moment I'm having trouble with Forge. Getting the right spec for the mappings always gives me trouble.

**Comment by cpburnz** [comment]
@nerosnm Support for 1.18.1 is completed. You can access it from the releases [here](https://github.com/cpburnz/minecraft-prometheus-exporter/releases/tag/mc1.18.1_v0.3.3) or on [Curse Forge](https://www.curseforge.com/minecraft/mc-mods/prometheus-exporter/files/) once it's approved over there.
