### ISSUE TITLE
Has anyone made a Grafana dashboard for this?

### ISSUE THREAD

**Issue by yesBad** [cpburnz/minecraft-prometheus-exporter#5]
My title pretty much explains it, if no one has then I guess I'll go try and make one :p

**Comment by kymppi** [comment]
hey, if you make it, could you link it here

**Comment by yesBad** [comment]
> hey, if you make it, could you link it here

Yeah that was the plan :)

**Comment by randombk** [comment]
Here is the one I built: https://grafana.com/grafana/dashboards/16508
![Screenshot from 2022-06-26 18-51-42](https://user-images.githubusercontent.com/1633923/175845947-ba5c15f5-6ae0-40c7-a34b-8796ecf5b64c.jpg)

**Comment by kymppi** [comment]
Wow, looks awesome 👏

**Comment by Maelstromeous** [comment]
@cpburnz would it be possible to add this to the readme.md as an example? This grafana dash is an incredible resource and I have no doubt many would use it!

**Comment by cpburnz** [comment]
randombk's dashboard is now referenced in the README.md.

**Comment by Neboer** [comment]
> Here is the one I built: https://grafana.com/grafana/dashboards/16508 ![Screenshot from 2022-06-26 18-51-42](https://user-images.githubusercontent.com/1633923/175845947-ba5c15f5-6ae0-40c7-a34b-8796ecf5b64c.jpg)

hello, I noticed that your dashboard have some part(tps) which isn't work in newer version of Grafana and Prometheus, Cound you please update it?

![image](https://github.com/cpburnz/minecraft-prometheus-exporter/assets/43609792/b66f7cb4-0418-41d0-9ae9-09325a8658f1)

**Comment by S0ndz** [comment]
> > Here is the one I built: https://grafana.com/grafana/dashboards/16508 ![Screenshot from 2022-06-26 18-51-42](https://user-images.githubusercontent.com/1633923/175845947-ba5c15f5-6ae0-40c7-a34b-8796ecf5b64c.jpg)
> 
> hello, I noticed that your dashboard have some part(tps) which isn't work in newer version of Grafana and Prometheus, Cound you please update it?
> 
> ![image](https://private-user-images.githubusercontent.com/43609792/317122977-b66f7cb4-0418-41d0-9ae9-09325a8658f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MjAwNzcsIm5iZiI6MTcyNDUxOTc3NywicGF0aCI6Ii80MzYwOTc5Mi8zMTcxMjI5NzctYjY2ZjdjYjQtMDQxOC00MWQwLTlhZTktMDkzMjVhODY1OGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDE3MTYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNjNiYmIyMDUyMmM4YjQ2MDVjN2FhM2U4ZWIzMzQ0YzQyOWEwZjgwN2VkNmIzOTY4MzViZDA3YzY4MTEyN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pO4OQZmMO6PX_KmgImucE2CzEV_VHoDkb603bWnT75U)

Can confirm, having the same issue with Grafana 11 and the latest version of prometheus and the prometheus exporter mod. Downgrading to Grafana 9.5 fixes the issue.

**Comment by Maelstromeous** [comment]
I made one recently that had most of the features, will upload to Grafana shortly. I'll also propose an edit to the readme to update to this new dashboard.

**Comment by Maelstromeous** [comment]
Apparently my grafana version is "too old" despite the fact I'm using the latest image....

Attached is my dashboard's model JSON. You'll have to change some things like the IP address but otherwise should work. 
[minecraft-fabric.json](https://github.com/user-attachments/files/16739907/minecraft-fabric.json)

**Comment by S0ndz** [comment]
Thanks for the link, sadly I need a 1.7.10 forge version... Still hoping RandomBK is able to update his dashboard to a newer version
